### ISSUE TITLE
console error

### ISSUE THREAD

**Issue by optimusprime338** [TheNewHEROBRINEX/AllAPILoader#1]
using latest PMMP API3/blocks branch:-
Fatal error: Declaration of TheNewHEROBRINE\AllAPILoader\Loaders\AllPharPluginLoader::getPluginDescription(string $file) must be compatible with pocketmine\plugin\PluginLoader::getPluginDescription($file) in phar:///plugins/AllAPILoader.phar/src/TheNewHEROBRINE/AllAPILoader/Loaders/AllPharPluginLoader.php on line 0

**Comment by TheNewHEROBRINEX** [comment]
I updated the plugin try the latest version
